class QuadrupedCTRL(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2022-08-22 23:09:02 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 3
        self.input_vars = ['']

    def move(self, ):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['stand', 'goal', 'jump', 'lie', 'loc']
        """
        output = dict()
        if self.state == 0:
            if True:
                self.state = 1

                output["stand"] = False
                output["goal"] = False
                output["jump"] = False
                output["lie"] = False
                output["loc"] = 'X3'
        elif self.state == 1:
            if True:
                self.state = 2

                output["stand"] = False
                output["goal"] = True
                output["jump"] = False
                output["lie"] = False
                output["loc"] = 'X6'
        elif self.state == 2:
            if True:
                self.state = 2

                output["stand"] = False
                output["goal"] = True
                output["jump"] = False
                output["lie"] = False
                output["loc"] = 'X6'
        elif self.state == 3:
            if True:
                self.state = 0

                output["stand"] = False
                output["goal"] = False
                output["jump"] = False
                output["lie"] = False
                output["loc"] = 'X0'
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, ):
        raise ValueError("Unrecognized input: " + ().format())
